### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by hasanalizxc** [nicholasadamou/OnionPi#1]
Dear nicholasadamou,

Hope you are fine.

I looked your OnionPi project and liked but i have a question. I have to ask this, sorry.

Are you member of 5Eyes, 9Eyes and 14Eyes?

Thanks.

**Comment by nicholasadamou** [comment]
Thank you for your message. No I am not a member of those organizations you've listed.

@hasanalizxc 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hasanalizxc** [comment]
> Thank you for your message. No I am not a member of those organizations you've listed.
> 
> @hasanalizxc
> 
> Sent with [GitHawk](http://githawk.com)

@nicholasadamou Thank for your interest and quick reply. I have a pi3 modelB and will try this project as soon as.
