### ISSUE TITLE
Clean install error:

### ISSUE THREAD

**Issue by Sc4nd4l** [nicholasadamou/OnionPi#2]
Hi, 
Trying to launch the script, but getting: 

> This script will configure your Raspberry Pi as a wireless access point and to connect to any OPEN WiFi access point.
Press [Enter] to begin, [Ctrl-C] to abort...
./setup_pifi.sh: line 120: update: command not found
./setup_pifi.sh: line 121: upgrade: command not found

>

**Comment by nicholasadamou** [comment]
`setup_pifi.sh` does not exist within this repository. Please make sure to `pull` from `master` and try again.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sc4nd4l** [comment]
Cheers!
